---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/login":
    post:
      summary: Login
      tags:
      - User
      parameters: []
      responses:
        '200':
          description: Login Successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: aimemalaika@gmail.com
                password:
                  type: string
                  example: '12345678'
              required:
              - email
              - password
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
