---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/blogs":
    post:
      summary: Creates a blog
      tags:
      - Blogs
      parameters: []
      responses:
        '201':
          description: blog created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
              required:
              - title
              - content
  "/login":
    post:
      summary: Login
      tags:
      - User
      parameters: []
      responses:
        '200':
          description:
            message: Login Successful
            auth_token: ds4324323h2h4h32h432
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: aimemalaika@gmail.com
                password:
                  type: string
                  example: '12345678'
              required:
              - email
              - password
  "/users":
    get:
      summary: Get all users
      tags:
      - User
      responses:
        '200':
          description: Get all users
  "/users/{id}":
    get:
      summary: Get a user
      tags:
      - User
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Get a user
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000/api/v1
